CRITICAL - 2024-06-15 10:33:30 --> ErrorException: Undefined variable $toke
in APPPATH\Controllers\Peternak.php on line 35.
 1 APPPATH\Controllers\Peternak.php(35): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $toke', 'C:\\xampp\\htdocs\\sobatx\\app\\Controllers\\Peternak.php', 35)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 10:33:48 --> GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

in VENDORPATH\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113.
 1 VENDORPATH\guzzlehttp\guzzle\src\Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), null, [], null)
 2 VENDORPATH\guzzlehttp\promises\src\Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
 3 VENDORPATH\guzzlehttp\promises\src\Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), null)
 4 VENDORPATH\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
 5 VENDORPATH\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
 6 VENDORPATH\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
 7 VENDORPATH\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
 8 VENDORPATH\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
 9 VENDORPATH\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
10 VENDORPATH\guzzlehttp\guzzle\src\Client.php(124): GuzzleHttp\Promise\Promise->wait()
11 VENDORPATH\google\auth\src\HttpHandler\Guzzle6HttpHandler.php(47): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), [...])
12 VENDORPATH\google\auth\src\OAuth2.php(551): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
13 VENDORPATH\google\apiclient\src\Google\Client.php(215): Google\Auth\OAuth2->fetchAuthToken(Object(Google\Auth\HttpHandler\Guzzle7HttpHandler))
14 APPPATH\Controllers\Peternak.php(34): Google_Client->fetchAccessTokenWithAuthCode('4/0ATx3LY6nIhkPIokAuDTbO81_Dr_wmaOF0ezTruoiSg-6CgRmJa1Xf3lqAaXu-FK6udlx6g')
15 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
16 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
17 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
18 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
19 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 10:34:44 --> GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

in VENDORPATH\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113.
 1 VENDORPATH\guzzlehttp\guzzle\src\Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), null, [], null)
 2 VENDORPATH\guzzlehttp\promises\src\Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
 3 VENDORPATH\guzzlehttp\promises\src\Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), null)
 4 VENDORPATH\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
 5 VENDORPATH\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
 6 VENDORPATH\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
 7 VENDORPATH\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
 8 VENDORPATH\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
 9 VENDORPATH\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
10 VENDORPATH\guzzlehttp\guzzle\src\Client.php(124): GuzzleHttp\Promise\Promise->wait()
11 VENDORPATH\google\auth\src\HttpHandler\Guzzle6HttpHandler.php(47): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), [...])
12 VENDORPATH\google\auth\src\OAuth2.php(551): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
13 VENDORPATH\google\apiclient\src\Google\Client.php(215): Google\Auth\OAuth2->fetchAuthToken(Object(Google\Auth\HttpHandler\Guzzle7HttpHandler))
14 APPPATH\Controllers\Peternak.php(34): Google_Client->fetchAccessTokenWithAuthCode('4/0ATx3LY45vDeMwJYb_Wm7-aCUXYPLttDIvIVN3Ecd3LhIwJ4miQDaUFLqES5aPWYJIysoiw')
15 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
16 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
17 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
18 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
19 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 10:34:52 --> GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

in VENDORPATH\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113.
 1 VENDORPATH\guzzlehttp\guzzle\src\Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), null, [], null)
 2 VENDORPATH\guzzlehttp\promises\src\Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
 3 VENDORPATH\guzzlehttp\promises\src\Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), null)
 4 VENDORPATH\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
 5 VENDORPATH\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
 6 VENDORPATH\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
 7 VENDORPATH\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
 8 VENDORPATH\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
 9 VENDORPATH\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
10 VENDORPATH\guzzlehttp\guzzle\src\Client.php(124): GuzzleHttp\Promise\Promise->wait()
11 VENDORPATH\google\auth\src\HttpHandler\Guzzle6HttpHandler.php(47): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), [...])
12 VENDORPATH\google\auth\src\OAuth2.php(551): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
13 VENDORPATH\google\apiclient\src\Google\Client.php(215): Google\Auth\OAuth2->fetchAuthToken(Object(Google\Auth\HttpHandler\Guzzle7HttpHandler))
14 APPPATH\Controllers\Peternak.php(34): Google_Client->fetchAccessTokenWithAuthCode('4/0ATx3LY45vDeMwJYb_Wm7-aCUXYPLttDIvIVN3Ecd3LhIwJ4miQDaUFLqES5aPWYJIysoiw')
15 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
16 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
17 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
18 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
19 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 10:40:10 --> InvalidArgumentException: Invalid code
in VENDORPATH\google\apiclient\src\Google\Client.php on line 207.
 1 APPPATH\Controllers\Peternak.php(34): Google_Client->fetchAccessTokenWithAuthCode(null)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 10:59:05 --> Error: Call to a member function save() on null
in APPPATH\Controllers\Peternak.php on line 59.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:04:39 --> Error: Object of class App\Models\M_User could not be converted to string
in APPPATH\Controllers\Peternak.php on line 60.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:05:07 --> GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

in VENDORPATH\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113.
 1 VENDORPATH\guzzlehttp\guzzle\src\Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), null, [], null)
 2 VENDORPATH\guzzlehttp\promises\src\Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
 3 VENDORPATH\guzzlehttp\promises\src\Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), null)
 4 VENDORPATH\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
 5 VENDORPATH\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
 6 VENDORPATH\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
 7 VENDORPATH\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
 8 VENDORPATH\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
 9 VENDORPATH\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
10 VENDORPATH\guzzlehttp\guzzle\src\Client.php(124): GuzzleHttp\Promise\Promise->wait()
11 VENDORPATH\google\auth\src\HttpHandler\Guzzle6HttpHandler.php(47): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), [...])
12 VENDORPATH\google\auth\src\OAuth2.php(551): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
13 VENDORPATH\google\apiclient\src\Google\Client.php(215): Google\Auth\OAuth2->fetchAuthToken(Object(Google\Auth\HttpHandler\Guzzle7HttpHandler))
14 APPPATH\Controllers\Peternak.php(38): Google_Client->fetchAccessTokenWithAuthCode('4/0ATx3LY4MYQCeJ2y8EAy1oZIJNwEvYnpgo6F8dsAU7IyzjgjS6UV_irZsxqcaagynnuXTWg')
15 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
16 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
17 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
18 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
19 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 11:27:32 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\app\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(60): App\Models\M_User->saveDataUser(Array)
#6 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#7 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-06-15 11:27:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\Peternak.php(60): App\Models\M_User->saveDataUser([...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:27:32 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:27:32\', \'2024-06-15 11:27:32\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:27:32\', \'2024-06-15 11:27:32\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\Peternak.php(60): App\Models\M_User->saveDataUser([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:27:32 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:27:32\', \'2024-06-15 11:27:32\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:27:32\', \'2024-06-15 11:27:32\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:27:32\', \'2024-06-15 11:27:32\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\Peternak.php(60): App\Models\M_User->saveDataUser([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 11:29:30 --> mysqli_sql_exception: Unknown column 'tbl_user.deleted_at' in 'where clause' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\sobatx\system\Model.php(714): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\sobatx\system\BaseModel.php(710): CodeIgniter\Model->shouldUpdate(Array)
#7 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-06-15 11:29:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 2 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 3 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 4 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 5 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:29:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 3 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 4 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 5 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 6 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 7 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:29:30 --> [Caused by] mysqli_sql_exception: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 4 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 5 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 6 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 7 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 8 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 11:31:17 --> mysqli_sql_exception: Unknown column 'tbl_user.deleted_at' in 'where clause' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\sobatx\system\Model.php(714): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\sobatx\system\BaseModel.php(710): CodeIgniter\Model->shouldUpdate(Array)
#7 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-06-15 11:31:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 2 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 3 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 4 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 5 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:31:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 3 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 4 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 5 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 6 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 7 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:31:17 --> [Caused by] mysqli_sql_exception: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 4 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 5 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 6 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 7 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 8 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 11:31:51 --> mysqli_sql_exception: Unknown column 'tbl_user.deleted_at' in 'where clause' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\sobatx\system\Model.php(714): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\sobatx\system\BaseModel.php(710): CodeIgniter\Model->shouldUpdate(Array)
#7 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-06-15 11:31:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 2 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 3 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 4 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 5 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:31:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 3 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 4 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 5 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 6 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 7 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:31:51 --> [Caused by] mysqli_sql_exception: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 4 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 5 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 6 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 7 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 8 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 11:33:03 --> mysqli_sql_exception: Unknown column 'tbl_user.deleted_at' in 'where clause' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\sobatx\system\Model.php(714): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\sobatx\system\BaseModel.php(710): CodeIgniter\Model->shouldUpdate(Array)
#7 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-06-15 11:33:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 2 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 3 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 4 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 5 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:33:03 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 3 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 4 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 5 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 6 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 7 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:33:03 --> [Caused by] mysqli_sql_exception: Unknown column 'tbl_user.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = \'114716822027796441665\'
AND `tbl_user`.`deleted_at` IS NULL')
 4 SYSTEMPATH\Database\BaseBuilder.php(1700): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `tbl_user`
WHERE `id_user` = :id_user:
AND `tbl_user`.`deleted_at` IS NULL', [...], false)
 5 SYSTEMPATH\Model.php(624): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 6 SYSTEMPATH\Model.php(714): CodeIgniter\Model->countAllResults()
 7 SYSTEMPATH\BaseModel.php(710): CodeIgniter\Model->shouldUpdate([...])
 8 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 11:35:10 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sobatx\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sobatx\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sobatx\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#11 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-06-15 11:35:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:35:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:35:10\', \'2024-06-15 11:35:10\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:35:10\', \'2024-06-15 11:35:10\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:35:10 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:35:10\', \'2024-06-15 11:35:10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:35:10\', \'2024-06-15 11:35:10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:35:10\', \'2024-06-15 11:35:10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Peternak.php(62): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:51:07 --> ErrorException: Undefined variable $peternak
in APPPATH\Controllers\Peternak.php on line 59.
 1 APPPATH\Controllers\Peternak.php(59): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $peternak', 'C:\\xampp\\htdocs\\sobatx\\app\\Controllers\\Peternak.php', 59)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:52:36 --> Error: Call to a member function save() on null
in APPPATH\Controllers\Peternak.php on line 59.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 11:55:19 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sobatx\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sobatx\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sobatx\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#11 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-06-15 11:55:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:55:19 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:55:19\', \'2024-06-15 11:55:19\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:55:19\', \'2024-06-15 11:55:19\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 11:55:19 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:55:19\', \'2024-06-15 11:55:19\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:55:19\', \'2024-06-15 11:55:19\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 11:55:19\', \'2024-06-15 11:55:19\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 12:00:57 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sobatx\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sobatx\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sobatx\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#11 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-06-15 12:00:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:00:57 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:00:57\', \'2024-06-15 12:00:57\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:00:57\', \'2024-06-15 12:00:57\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:00:57 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:00:57\', \'2024-06-15 12:00:57\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:00:57\', \'2024-06-15 12:00:57\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:00:57\', \'2024-06-15 12:00:57\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:09:42 --> ErrorException: Maximum execution time of 60 seconds exceeded
in VENDORPATH\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 595.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-06-15 12:10:14 --> ErrorException: Undefined variable $modeluser
in APPPATH\Controllers\Peternak.php on line 50.
 1 APPPATH\Controllers\Peternak.php(50): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $modeluser', 'C:\\xampp\\htdocs\\sobatx\\app\\Controllers\\Peternak.php', 50)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:16:18 --> ErrorException: Maximum execution time of 60 seconds exceeded
in VENDORPATH\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 595.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-06-15 12:19:36 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sobatx\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sobatx\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sobatx\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(77): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#11 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-06-15 12:19:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :foto_user:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Peternak.php(77): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:19:36 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'2024-06-15 12:19:36\', \'2024-06-15 12:19:36\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'2024-06-15 12:19:36\', \'2024-06-15 12:19:36\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :foto_user:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Peternak.php(77): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:19:36 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'2024-06-15 12:19:36\', \'2024-06-15 12:19:36\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'2024-06-15 12:19:36\', \'2024-06-15 12:19:36\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'2024-06-15 12:19:36\', \'2024-06-15 12:19:36\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :foto_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Peternak.php(77): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:23:43 --> ErrorException: Trying to access array offset on value of type int
in APPPATH\Controllers\Peternak.php on line 76.
 1 APPPATH\Controllers\Peternak.php(76): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type int', 'C:\\xampp\\htdocs\\sobatx\\app\\Controllers\\Peternak.php', 76)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:26:38 --> Error: Call to undefined function App\Controllers\str()
in APPPATH\Controllers\Peternak.php on line 76.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 12:41:44 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sobatx\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sobatx\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sobatx\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(78): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#11 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-06-15 12:41:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :foto_user:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Peternak.php(78): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:41:44 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'2024-06-15 12:41:44\', \'2024-06-15 12:41:44\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'2024-06-15 12:41:44\', \'2024-06-15 12:41:44\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :foto_user:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Peternak.php(78): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:41:44 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'2024-06-15 12:41:44\', \'2024-06-15 12:41:44\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'2024-06-15 12:41:44\', \'2024-06-15 12:41:44\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'2024-06-15 12:41:44\', \'2024-06-15 12:41:44\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `foto_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :foto_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Peternak.php(78): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:45:45 --> InvalidArgumentException: Invalid code
in VENDORPATH\google\apiclient\src\Google\Client.php on line 207.
 1 APPPATH\Controllers\Peternak.php(40): Google_Client->fetchAccessTokenWithAuthCode(null)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 12:49:44 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\app\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser(Array)
#6 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#7 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-06-15 12:49:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser([...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:49:44 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:49:44\', \'2024-06-15 12:49:44\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:49:44\', \'2024-06-15 12:49:44\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:49:44 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:49:44\', \'2024-06-15 12:49:44\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:49:44\', \'2024-06-15 12:49:44\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:49:44\', \'2024-06-15 12:49:44\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:50:53 --> GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

in VENDORPATH\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113.
 1 VENDORPATH\guzzlehttp\guzzle\src\Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), null, [], null)
 2 VENDORPATH\guzzlehttp\promises\src\Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
 3 VENDORPATH\guzzlehttp\promises\src\Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), null)
 4 VENDORPATH\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
 5 VENDORPATH\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
 6 VENDORPATH\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
 7 VENDORPATH\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
 8 VENDORPATH\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
 9 VENDORPATH\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
10 VENDORPATH\guzzlehttp\guzzle\src\Client.php(124): GuzzleHttp\Promise\Promise->wait()
11 VENDORPATH\google\auth\src\HttpHandler\Guzzle6HttpHandler.php(47): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), [...])
12 VENDORPATH\google\auth\src\OAuth2.php(551): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
13 VENDORPATH\google\apiclient\src\Google\Client.php(215): Google\Auth\OAuth2->fetchAuthToken(Object(Google\Auth\HttpHandler\Guzzle7HttpHandler))
14 APPPATH\Controllers\Peternak.php(40): Google_Client->fetchAccessTokenWithAuthCode('4/0ATx3LY7RdnxIbtSgk4SiHhgNXQwsSwlnPE-YiMnObbRMGtshl57qpnr_Iv9Q89s7nXz1Dg')
15 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
16 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
17 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
18 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
19 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 12:51:22 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\app\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser(Array)
#6 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#7 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-06-15 12:51:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser([...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:51:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:51:22\', \'2024-06-15 12:51:22\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:51:22\', \'2024-06-15 12:51:22\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:51:22 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:51:22\', \'2024-06-15 12:51:22\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:51:22\', \'2024-06-15 12:51:22\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:51:22\', \'2024-06-15 12:51:22\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:52:36 --> GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

in VENDORPATH\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113.
 1 VENDORPATH\guzzlehttp\guzzle\src\Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), null, [], null)
 2 VENDORPATH\guzzlehttp\promises\src\Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
 3 VENDORPATH\guzzlehttp\promises\src\Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), null)
 4 VENDORPATH\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
 5 VENDORPATH\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
 6 VENDORPATH\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
 7 VENDORPATH\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
 8 VENDORPATH\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
 9 VENDORPATH\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
10 VENDORPATH\guzzlehttp\guzzle\src\Client.php(124): GuzzleHttp\Promise\Promise->wait()
11 VENDORPATH\google\auth\src\HttpHandler\Guzzle6HttpHandler.php(47): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), [...])
12 VENDORPATH\google\auth\src\OAuth2.php(551): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
13 VENDORPATH\google\apiclient\src\Google\Client.php(215): Google\Auth\OAuth2->fetchAuthToken(Object(Google\Auth\HttpHandler\Guzzle7HttpHandler))
14 APPPATH\Controllers\Peternak.php(40): Google_Client->fetchAccessTokenWithAuthCode('4/0ATx3LY5pJeVEl_sh7OjsDzeNfO3jl5INa8FPzll5PwTr3dxlY3RqtPWW6FpASG-WPP7L3w')
15 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
16 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
17 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
18 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
19 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 12:53:49 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\app\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(64): App\Models\M_User->saveDataUser(Array)
#6 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#7 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-06-15 12:53:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\Peternak.php(64): App\Models\M_User->saveDataUser([...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:53:49 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:53:49\', \'2024-06-15 12:53:49\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:53:49\', \'2024-06-15 12:53:49\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\Peternak.php(64): App\Models\M_User->saveDataUser([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:53:49 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:53:49\', \'2024-06-15 12:53:49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:53:49\', \'2024-06-15 12:53:49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:53:49\', \'2024-06-15 12:53:49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\Peternak.php(64): App\Models\M_User->saveDataUser([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 12:55:28 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\app\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(64): App\Models\M_User->saveDataUser(Array)
#6 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#7 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-06-15 12:55:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\Peternak.php(64): App\Models\M_User->saveDataUser([...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:55:28 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:55:28\', \'2024-06-15 12:55:28\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:55:28\', \'2024-06-15 12:55:28\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\Peternak.php(64): App\Models\M_User->saveDataUser([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:55:28 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:55:28\', \'2024-06-15 12:55:28\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:55:28\', \'2024-06-15 12:55:28\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:55:28\', \'2024-06-15 12:55:28\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\Peternak.php(64): App\Models\M_User->saveDataUser([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 12:58:08 --> mysqli_sql_exception: Duplicate entry '1111154430' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\app\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(73): App\Models\M_User->saveDataUser(Array)
#6 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#7 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-06-15 12:58:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1111154430' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\Peternak.php(73): App\Models\M_User->saveDataUser([...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:58:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1111154430' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'111115443078833748165\', \'SobatX\', \'sobatx.mail@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocJYsmIejUvJJLayNIX0PvDyVwWRKP43QOP8zQaDluTCEmRapw=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:58:08\', \'2024-06-15 12:58:08\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'111115443078833748165\', \'SobatX\', \'sobatx.mail@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocJYsmIejUvJJLayNIX0PvDyVwWRKP43QOP8zQaDluTCEmRapw=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:58:08\', \'2024-06-15 12:58:08\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\Peternak.php(73): App\Models\M_User->saveDataUser([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 12:58:08 --> [Caused by] mysqli_sql_exception: Duplicate entry '1111154430' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'111115443078833748165\', \'SobatX\', \'sobatx.mail@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocJYsmIejUvJJLayNIX0PvDyVwWRKP43QOP8zQaDluTCEmRapw=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:58:08\', \'2024-06-15 12:58:08\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'111115443078833748165\', \'SobatX\', \'sobatx.mail@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocJYsmIejUvJJLayNIX0PvDyVwWRKP43QOP8zQaDluTCEmRapw=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:58:08\', \'2024-06-15 12:58:08\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'111115443078833748165\', \'SobatX\', \'sobatx.mail@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocJYsmIejUvJJLayNIX0PvDyVwWRKP43QOP8zQaDluTCEmRapw=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 12:58:08\', \'2024-06-15 12:58:08\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\Peternak.php(73): App\Models\M_User->saveDataUser([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 13:01:39 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\app\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(65): App\Models\M_User->saveDataUser(Array)
#6 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#7 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-06-15 13:01:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:)', [...], false)
 2 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\Peternak.php(65): App\Models\M_User->saveDataUser([...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:01:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:)', [...], false)
 4 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\Peternak.php(65): App\Models\M_User->saveDataUser([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:01:39 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:)', [...], false)
 5 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\Peternak.php(65): App\Models\M_User->saveDataUser([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 13:02:56 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\app\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser(Array)
#6 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#7 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#8 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-06-15 13:02:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:)', [...], false)
 2 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 3 APPPATH\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser([...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:02:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:)', [...], false)
 4 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 5 APPPATH\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:02:56 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`) VALUES (:id_user:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:)', [...], false)
 5 APPPATH\Models\M_User.php(29): CodeIgniter\Database\BaseBuilder->insert([...])
 6 APPPATH\Controllers\Peternak.php(66): App\Models\M_User->saveDataUser([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 13:06:23 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sobatx\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sobatx\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sobatx\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(68): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#11 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-06-15 13:06:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Peternak.php(68): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:06:23 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:06:23\', \'2024-06-15 13:06:23\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:06:23\', \'2024-06-15 13:06:23\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Peternak.php(68): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:06:23 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:06:23\', \'2024-06-15 13:06:23\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:06:23\', \'2024-06-15 13:06:23\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:06:23\', \'2024-06-15 13:06:23\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Peternak.php(68): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 13:09:11 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sobatx\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sobatx\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sobatx\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(68): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#11 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-06-15 13:09:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Peternak.php(68): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:09:11 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:09:11\', \'2024-06-15 13:09:11\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:09:11\', \'2024-06-15 13:09:11\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Peternak.php(68): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:09:11 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:09:11\', \'2024-06-15 13:09:11\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:09:11\', \'2024-06-15 13:09:11\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:09:11\', \'2024-06-15 13:09:11\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Peternak.php(68): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:11:45 --> TypeError: CodeIgniter\Database\BaseBuilder::get(): Argument #1 ($limit) must be of type ?int, array given, called in C:\xampp\htdocs\sobatx\system\Model.php on line 872
in SYSTEMPATH\Database\BaseBuilder.php on line 1608.
 1 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get([...])
 2 APPPATH\Controllers\Peternak.php(51): CodeIgniter\Model->__call('get', [...])
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:13:06 --> TypeError: CodeIgniter\Database\BaseBuilder::get(): Argument #1 ($limit) must be of type ?int, string given, called in C:\xampp\htdocs\sobatx\system\Model.php on line 872
in SYSTEMPATH\Database\BaseBuilder.php on line 1608.
 1 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get('id_user')
 2 APPPATH\Controllers\Peternak.php(51): CodeIgniter\Model->__call('get', [...])
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:16:40 --> TypeError: CodeIgniter\Database\BaseBuilder::get(): Argument #1 ($limit) must be of type ?int, string given, called in C:\xampp\htdocs\sobatx\system\Model.php on line 872
in SYSTEMPATH\Database\BaseBuilder.php on line 1608.
 1 SYSTEMPATH\Model.php(872): CodeIgniter\Database\BaseBuilder->get('id_user')
 2 APPPATH\Controllers\Peternak.php(50): CodeIgniter\Model->__call('get', [...])
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 13:19:10 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sobatx\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sobatx\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sobatx\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(65): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#11 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-06-15 13:19:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Peternak.php(65): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:19:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:19:10\', \'2024-06-15 13:19:10\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:19:10\', \'2024-06-15 13:19:10\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Peternak.php(65): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:19:10 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:19:10\', \'2024-06-15 13:19:10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:19:10\', \'2024-06-15 13:19:10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:19:10\', \'2024-06-15 13:19:10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Peternak.php(65): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 13:25:57 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sobatx\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sobatx\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sobatx\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#11 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-06-15 13:25:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:25:57 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:25:57\', \'2024-06-15 13:25:57\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:25:57\', \'2024-06-15 13:25:57\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:25:57 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:25:57\', \'2024-06-15 13:25:57\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:25:57\', \'2024-06-15 13:25:57\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:25:57\', \'2024-06-15 13:25:57\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
ERROR - 2024-06-15 13:26:51 --> mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY' in C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sobatx\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\sobatx\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\sobatx\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\sobatx\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sobatx\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sobatx\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sobatx\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sobatx\app\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
#10 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
#11 C:\xampp\htdocs\sobatx\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sobatx\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sobatx\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-06-15 13:26:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:26:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:26:51\', \'2024-06-15 13:26:51\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:26:51\', \'2024-06-15 13:26:51\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
CRITICAL - 2024-06-15 13:26:51 --> [Caused by] mysqli_sql_exception: Duplicate entry '1147168220' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:26:51\', \'2024-06-15 13:26:51\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:26:51\', \'2024-06-15 13:26:51\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (\'114716822027796441665\', \'Ferdy Rahmat\', \'ferdyyrahmat@gmail.com\', \'\', \'\', \'\', \'https://lh3.googleusercontent.com/a/ACg8ocL1pTOLtcAPAPp5h89mD753TajbrnlB3bopQxEglUEdcGSKk4o_=s96-c\', \'1\', \'1\', \'0\', \'2024-06-15 13:26:51\', \'2024-06-15 13:26:51\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tbl_user` (`id_user`, `nama_user`, `email_user`, `alamat_user`, `no_hp`, `password`, `foto_user`, `akses_level`, `status`, `is_delete_user`, `created_at`, `updated_at`) VALUES (:id_user.1:, :nama_user:, :email_user:, :alamat_user:, :no_hp:, :password:, :foto_user:, :akses_level:, :status:, :is_delete_user:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Peternak.php(59): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Peternak->login_checker()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Peternak))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sobatx\\public\\index.php')
